[
  ../../modules/core/vars.nix
  ../../modules/core/system.nix
  ../../modules/core/network.nix
  ../../modules/core/boot.nix
  ../../modules/core/users.nix
  ../../modules/core/documentacion.nix
  ../../modules/core/bluetooth.nix
  ../../modules/core/audio.nix
  ../../modules/core/virtualizacion.nix

  ../../modules/infra/sops.nix
  ../../modules/infra/ssh.nix
  ../../modules/infra/impermanence.nix
  ../../modules/infra/git.nix

  ../../modules/programs/ai/opencode.nix
  ../../modules/programs/ai/litellm.nix
  ../../modules/programs/ai/llama.nix
  ../../modules/programs/android.nix
  ../../modules/programs/comunicacion/cliente.nix
  ../../modules/programs/comunicacion/thunderbird.nix
  ../../modules/programs/consigna/keepassxc.nix
  ../../modules/programs/escritorio/mango.nix
  ../../modules/programs/escritorio/sway.nix
  ../../modules/programs/escritorio/noctalia.nix
  ../../modules/programs/labctl.nix
  ../../modules/programs/lectura.nix
  ../../modules/programs/media/cliente.nix
  ../../modules/programs/navegadores/firefox.nix
  ../../modules/programs/navegadores/chomium.nix
  ../../modules/programs/navegadores/tor.nix
  ../../modules/programs/navegadores/qutebrowser.nix
  ../../modules/programs/nvim.nix
  ../../modules/programs/pkm.nix
  ../../modules/programs/shell/zsh.nix
  ../../modules/programs/shell/ranger.nix
  ../../modules/programs/shell/kitty.nix
  ../../modules/programs/shell/tmux.nix
  ../../modules/programs/shell/direnv.nix
  ../../modules/programs/shell/kmscon.nix
]
